name: Verify Perl on Darwin

on:
  push:
    branches: [ "macos" ]
  workflow_dispatch:

jobs:
  test-on-darwin:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: "5.38"

    - name: Run script and verify platform
      run: |
        perl test/RenameEx_test.pl native
